#!/bin/bash

. config

java -cp K3Translator.jar:bcel-5.2.jar  Translator es root_$VERSION/opt/amazon/ebook/booklet strings
java -cp K3Translator.jar:bcel-5.2.jar  Translator es root_$VERSION/opt/amazon/ebook/lib strings
