#!/bin/bash

. config

java -cp K3Translator.jar:bcel-5.2.jar  Translator es root_${VERSION}$1/opt/amazon/ebook/booklet strings$1
java -cp K3Translator.jar:bcel-5.2.jar  Translator es root_${VERSION}$1/opt/amazon/ebook/lib strings$1
