#!/bin/bash

. config

[ -d overlay ] || mkdir overlay
rm -f overlay/*.jar

./translation2transjar
java -cp K3Translator.jar:bcel-5.2.jar Translator td root_$VERSION/opt/amazon/ebook/lib translation.jar overlay .
java -cp K3Translator.jar:bcel-5.2.jar Translator td root_$VERSION/opt/amazon/ebook/booklet translation.jar overlay .
