#!/bin/bash

. config

dest=install/usr/share/locale/en_GB/LC_MESSAGES
rm -f "$dest"/*.mo
[ -d "$dest" ] || mkdir -p "$dest"

find translation_$VERSION/po -name '*.po' -exec sh -c "
fn=\$(basename {});
fn=\${fn%.po}.mo;
cat {} | sed 's/^\\(.Language: \\)[-_.A-Za-z]\\+\\(...\\)\$/\\1en\\2/g' | msgfmt /dev/stdin -o $dest/\$fn" \;
